get().then((result) => {
    console.log(result);   
}).catch((err) => {
    console.log(err);
});